// <auto-generated />
using System;
using HyderabadBazaar.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyderabadBazaar.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HyderabadBazaar.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Authentic Hyderabadi biryani masalas and spices",
                            ImageUrl = "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
                            IsActive = true,
                            Name = "Biryani Spices"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Famous Hyderabadi pearls and traditional jewellery",
                            ImageUrl = "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400",
                            IsActive = true,
                            Name = "Pearls & Jewellery"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bidriware, Nirmal paintings and local handicrafts",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            IsActive = true,
                            Name = "Handicrafts"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pochampally Ikat, Gadwal sarees and Hyderabadi fabrics",
                            ImageUrl = "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400",
                            IsActive = true,
                            Name = "Textiles & Ikat"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Latest gadgets and electronics from Hyderabad tech hub",
                            ImageUrl = "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Double ka meetha, Qubani ka meetha and traditional sweets",
                            ImageUrl = "https://images.unsplash.com/photo-1571167530149-c1105da4f3b9?w=400",
                            IsActive = true,
                            Name = "Hyderabadi Sweets"
                        });
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic Hyderabadi biryani masala blend from the legendary Shah Ghouse restaurant recipe. Perfect spice mix for dum biryani.",
                            DiscountPrice = 249m,
                            ImageUrl = "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
                            IsActive = true,
                            Name = "Shah Ghouse Biryani Masala",
                            Price = 299m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 1245,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete spice kit from Pista House — Hyderabad's iconic biryani chain. Includes whole spices and masala blend.",
                            DiscountPrice = 389m,
                            ImageUrl = "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?w=400",
                            IsActive = true,
                            Name = "Pista House Biryani Spice Kit",
                            Price = 450m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 876,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ready-mix for the famous Mirchi ka Salan — the traditional accompaniment to Hyderabadi biryani.",
                            DiscountPrice = 149m,
                            ImageUrl = "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
                            IsActive = true,
                            Name = "Hyderbadi Mirchi ka Salan Mix",
                            Price = 180m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 532,
                            Stock = 200
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pure Kashmiri saffron, essential for authentic Hyderabadi biryani color and aroma. 2g pack.",
                            DiscountPrice = 520m,
                            ImageUrl = "https://images.unsplash.com/photo-1606914501449-5a96b6ce24ca?w=400",
                            IsActive = true,
                            Name = "Saffron (Kesar) Premium Grade",
                            Price = 599m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 2103,
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic freshwater pearl necklace set with matching earrings. Sourced from Hyderabad's famous Laad Bazaar.",
                            DiscountPrice = 3999m,
                            ImageUrl = "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400",
                            IsActive = true,
                            Name = "Hyderabadi Pearl Necklace Set",
                            Price = 4500m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 341,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handcrafted Kundan choker with meenakari work — traditional Hyderabadi jewellery art form.",
                            DiscountPrice = 7200m,
                            ImageUrl = "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
                            IsActive = true,
                            Name = "Kundan Choker Necklace",
                            Price = 8500m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 189,
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Certified South Sea pearl studs, hand-picked from Hyderabad's Mangatrai Pearls collection.",
                            DiscountPrice = 1899m,
                            ImageUrl = "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
                            IsActive = true,
                            Name = "South Sea Pearl Stud Earrings",
                            Price = 2200m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 467,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic Bidar silver inlay work vase — UNESCO-recognized craft. Each piece unique and handmade.",
                            DiscountPrice = 2499m,
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            IsActive = true,
                            Name = "Bidriware Flower Vase",
                            Price = 2800m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 213,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hand-painted Nirmal toy-style decorative box with traditional Telangana folk art motifs.",
                            DiscountPrice = 999m,
                            ImageUrl = "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=400",
                            IsActive = true,
                            Name = "Nirmal Lacquerware Wooden Box",
                            Price = 1200m,
                            Rating = 4.5,
                            ReviewCount = 178,
                            Stock = 35
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large hand-painted Kalamkari fabric art with Charminar motif — pen-and-ink technique on cotton.",
                            DiscountPrice = 1499m,
                            ImageUrl = "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400",
                            IsActive = true,
                            Name = "Kalamkari Wall Hanging",
                            Price = 1800m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 295,
                            Stock = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pure silk Pochampally Ikat saree with traditional geometric patterns from Bhoodan Pochampally village.",
                            DiscountPrice = 9999m,
                            ImageUrl = "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400",
                            IsActive = true,
                            Name = "Pochampally Ikat Silk Saree",
                            Price = 12000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 156,
                            Stock = 15
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional Gadwal saree with pure zari border — lightweight for summer wear.",
                            DiscountPrice = 5499m,
                            ImageUrl = "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400",
                            IsActive = true,
                            Name = "Gadwal Cotton Silk Saree",
                            Price = 6500m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 234,
                            Stock = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handwoven khadi cotton kurta-pajama set with chikan embroidery — comfort meets heritage.",
                            DiscountPrice = 1799m,
                            ImageUrl = "https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=400",
                            IsActive = true,
                            Name = "Hyderabadi Khadi Kurta Set",
                            Price = 2200m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 412,
                            Stock = 50
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless Bluetooth headphones with 15hr battery. Popular choice in Hyderabad tech stores.",
                            DiscountPrice = 1499m,
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
                            IsActive = true,
                            Name = "boAt Rockerz 450 Headphones",
                            Price = 1999m,
                            Rating = 4.2999999999999998,
                            ReviewCount = 8923,
                            Stock = 120
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5G smartphone with 200MP camera. Best seller at Hyderabad's SP Road electronics market.",
                            DiscountPrice = 23999m,
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
                            IsActive = true,
                            Name = "Redmi Note 13 Pro",
                            Price = 26999m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 5634,
                            Stock = 75
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intel Core i5, 16GB RAM, 512GB SSD. Popular at Hyderabad's HITECH City offices.",
                            DiscountPrice = 57999m,
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
                            IsActive = true,
                            Name = "HP Pavilion Laptop 15",
                            Price = 62990m,
                            Rating = 4.5,
                            ReviewCount = 2341,
                            Stock = 30
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Iconic Karachi Bakery fruit biscuits — Hyderabad's most famous bakery since 1953. 400g pack.",
                            DiscountPrice = 285m,
                            ImageUrl = "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400",
                            IsActive = true,
                            Name = "Karachi Bakery Fruit Biscuits",
                            Price = 320m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 15234,
                            Stock = 200
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ready-to-make mix for Hyderabad's beloved bread pudding dessert — Double Ka Meetha.",
                            DiscountPrice = 169m,
                            ImageUrl = "https://images.unsplash.com/photo-1571167530149-c1105da4f3b9?w=400",
                            IsActive = true,
                            Name = "Double Ka Meetha Mix",
                            Price = 199m,
                            Rating = 4.5,
                            ReviewCount = 723,
                            Stock = 180
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium dried apricot dessert mix — a classic Hyderabadi wedding sweet. 500g pack.",
                            DiscountPrice = 399m,
                            ImageUrl = "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=400",
                            IsActive = true,
                            Name = "Qubani Ka Meetha (Apricot Dessert)",
                            Price = 450m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 445,
                            Stock = 90
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic slow-cooked haleem spice and grain mix, inspired by Pista House's award-winning recipe.",
                            DiscountPrice = 329m,
                            ImageUrl = "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
                            IsActive = true,
                            Name = "Haleem Mix (Pista House Style)",
                            Price = 380m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 3201,
                            Stock = 140
                        });
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Cart", b =>
                {
                    b.HasOne("HyderabadBazaar.API.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyderabadBazaar.API.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Order", b =>
                {
                    b.HasOne("HyderabadBazaar.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.OrderItem", b =>
                {
                    b.HasOne("HyderabadBazaar.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyderabadBazaar.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Product", b =>
                {
                    b.HasOne("HyderabadBazaar.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HyderabadBazaar.API.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
